contao-community-alliance/dc-general

- .check-author.yml
- composer.json
- src/ContaoCommunityAlliance/DcGeneral/DC_General.php
Contao 3.5 changed the required methods of \DataContainer by defining them as abstrac (See #106). This pull request adds them to `\Dc_General` by throwing an exception when calling them. The DCG does not the calls as far as I see.
> Fix incompatibility with Contao 3.5

- src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php
when you select an page in the popup window, you becomes the value as array
> fix for page tree select

- src/ContaoCommunityAlliance/DcGeneral/Contao/Dca/Builder/Legacy/LegacyDcaDataDefinitionBuilder.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php
The manual sorting did not work because the manual sorting attribute was not set for the group and sorting definition (Fix #115).
> Fix manual sorting

- contao/html/css/generalBreadcrumb.css
- contao/html/sass/generalBreadcrumb.scss
Hide first breadcrumb separater as an empty content causes to break icon and text (at least in Google Chrome).
> Hide first breadcrumb separater

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ParentView.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ViewHelpers.php
The sorting panel did not have any affects if a default sorting is defined. It would be added as additional sortings. This pull request starts the panel initialization with an empty sorting definition and will fallback to the defualt one.
> Do not use default sorting when panel initializes it.

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php
[0] does not make sense here.  $label is a string. The description is in getDescription() instead
To verify, let \ContaoCommunityAlliance\DcGeneral\DataDefinition\Definition\View\DefaultListingConfig::getShowColumns return true
> Fix: Only first letter of label shown

- src/ContaoCommunityAlliance/DcGeneral/Contao/Event/Subscriber.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Controller/ClipboardController.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ParentView.php
This pull requests fixes the copy of an item when no sorting property is used (See metamodels/core#743).
* It moves the base config sorting initialization to the `BackendViewPopulator` as the base config sorting is a base requirement for many cases. Here it's required to detect non manual sorting property in the ClipboardController. Afaik there's no case where it would cause an unexpected behaviour. Do you know any edge cases,  @discordier?
* It prevents the clipboard to handle such copy actions.
* It uses the still existing View::copy methods instead if no manual sorting property is used.
There is still an issue: 
* If there is a manual sorting property which is not used in the current view, it would be duplicated. So the same sorting value would exists. Can this break the manual sorting …
> Copy without manual sorting

- contao/config/autoload.php
- contao/templates/widget_filetree.html5
- contao/templates/widget_filetree_order.html5
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoBackendViewTemplate.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Widget/AbstractWidget.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Widget/FileTree.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Widget/FileTreeOrder.php
This pull requests enables the DcGeneral to handle the sorting of the fileTree as the first step to support https://github.com/MetaModels/attribute_file/issues/8.
It splits the fileTree into two widgets. The fileTree itself and the fileTreeOrderField. By this approach we don't have to hack the ContaoWidgetManager completely to handle non widget field input. Besides there's no separate magic writing into the database/model required.
**Todo:** To support legacy datacontainer definitions where should be a compatibility layer in the data definition builder to set the inputType of the orderField property.
> Support sorting in the fileTree

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/IdSerializer.php
- src/ContaoCommunityAlliance/DcGeneral/Data/ModelId.php
- src/ContaoCommunityAlliance/DcGeneral/Data/ModelIdInterface.php
As proposed in #85 this pull request provides an implemenation of a generic model id and would replace the IdSerializer in the future.
This implementation introduces the an interface and implemtation of it. This would make the transition between IdSerializer and ModelId easier.
The model id is implemented as an immutable object so that we can benefit from the characteristic advantages of an immutable object:
* Be sure that the object referes to the same model.
* Be sure a valid id exists (No empty provider name or id).
At the moment the IdSerializer is not replaced anywhere. This could be done afterwards if this pull request is accepted.
> Introduce a generic model id.

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/IdSerializer.php
Always set the modelId and provider no matter if anything is empty (#86, see metamodels/core#844).
> Always set the modelId and provider

- contao/templates/widget_filetree_order.html5
The id of the fileTreeOrder widget does not had the ctrl_* part of the id. So the fileTree oder doesn't work.
> Fix id of fileTreeOrder widget.

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Widget/FileTree.php
The `VERSION` constant does not store the bugfix level.
> Fix version compare.

- src/ContaoCommunityAlliance/DcGeneral/Contao/Event/Subscriber.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ParentView.php
This pull request fixes the sorting issues described in #154. Somehow this fix wasn't published to github but I fixed it some times ago...
The reintroducing of the sorting in the list and parent view is required as the `BaseConfigRegistry` does not react as I would expect from a registry. Instead of storing one instance it returns a new clone of a base registry.
My initial idea was that the sorting would get initialized in https://github.com/contao-community-alliance/dc-general/compare/contao-community-alliance:develop...dmolineus:fix/sorting-issues?expand=1#diff-c33729d7abe4e062a7b8b47101611198R353 globally so the next time getting the base config would contain the initialized sorting.
I was thinking about to provide a way to manipulate the template base config being stored in the …
> Properly initialize the sorting.

- src/ContaoCommunityAlliance/DcGeneral/Controller/SortingManager.php
- tests/ContaoCommunityAlliance/DcGeneral/Test/Controller/SortingManagerTest.php
This pull request provides a fix for #149. The sorting manager could create deltas which would exceed soon as it calculates the delta as difference between the current position and the next element.
If the difference is too big (f.e. the models here got deleted or moved at the end), the issue occurs.
This PR also fixes the (theoretical) issue that the default delta (128) being returned could be lesser than the number of items being moved.
> Prevent that the sorting manager creates exceeding deltas.

- contao/config/event_listeners.php
- contao/templates/dcbe_general_clipboard.html5
- src/ContaoCommunityAlliance/DcGeneral/Clipboard/AbstractItem.php
- src/ContaoCommunityAlliance/DcGeneral/Clipboard/Clipboard.php
- src/ContaoCommunityAlliance/DcGeneral/Clipboard/ClipboardInterface.php
- src/ContaoCommunityAlliance/DcGeneral/Clipboard/Filter.php
- src/ContaoCommunityAlliance/DcGeneral/Clipboard/Item.php
- src/ContaoCommunityAlliance/DcGeneral/Clipboard/ItemInterface.php
- src/ContaoCommunityAlliance/DcGeneral/Clipboard/UnsavedItem.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/CreateHandler.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Controller/ClipboardController.php
- src/ContaoCommunityAlliance/DcGeneral/Controller/ControllerInterface.php
- src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php
- tests/ContaoCommunityAlliance/DcGeneral/Test/ClipBoard/ClipboardTest.php
- tests/ContaoCommunityAlliance/DcGeneral/Test/ClipBoard/FilterTest.php
- tests/ContaoCommunityAlliance/DcGeneral/Test/ClipBoard/ItemTest.php
- tests/ContaoCommunityAlliance/DcGeneral/Test/ClipBoard/MockedAbstractItem.php
- tests/ContaoCommunityAlliance/DcGeneral/Test/ClipBoard/MockedFilter.php
- tests/ContaoCommunityAlliance/DcGeneral/Test/ClipBoard/MockedSessionStorage.php
This pull request rewrites some parts of the clipboard handling so that only valid `ModelIds` are used.
As discussed the `ItemInterface` got extended. Additional I had to add an `getDataProviderName` method as well for items without an model id.
It's not ready tested yet, just to inform that the work is basically done. Have a further look this weekend.
> Prepare clipboard to deal with model ids. 

- src/ContaoCommunityAlliance/DcGeneral/Contao/Dca/Builder/Legacy/LegacyDcaDataDefinitionBuilder.php
This pull request fixes the missing default sorting and grouping information. If no default sorting and grouping information is defined, it assumes the first sorting definition is the default one.
It fixes issue mentioned in https://github.com/MetaModels/core/issues/864#issuecomment-156238053.
> Fix missing default sorting and grouping information

- contao/html/images/clear-clipboard.svg
- contao/html/images/clipboard.svg
die ursprünglichen SVG-Icons waren "zu groß"
> zwei neue SVG-Icons von Kim (k-webdesign)

- src/ContaoCommunityAlliance/DcGeneral/DC/General.php
This hotfix is for Contao breadcrumb.
If provide parent table in the data container configuration is set, then will get Contao backend with the magic getter becomes the id from the parent entry.
SEE:
Contao 3.5:
https://github.com/contao/core/blob/master/system/modules/core/classes/Backend.php#L548
Contao 4.4:
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/classes/Backend.php#L510
> [RTM] Find the parent id for the Contao breadcrumb

- src/ContaoCommunityAlliance/DcGeneral/Contao/Dca/Palette/LegacyPalettesParser.php
When we have a selectable sub selector, this has don´t work. This pull request is for work it.
As example what i mean here. By the Contao module news by news setting. Their is an selectable sub selector field `source`. You can switch here the sources with a radio button menu.
> [RTM] Add missing selectable sub selector to the sub palette parser

- contao/backend/generalfile.php
- contao/config/config.php
- contao/templates/widget_filetree.html5
- contao/templates/widget_treepicker_popup.html5
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/FileSelect.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Widget/FileTree.php
This is useful if you want to select a file and its property e. g. an onload callback is defined. In the callback method you want to use the active record, which is not supported before and now works. The data container is now a Dc-combat, before that the data container was a Dc-general.
This feature is the right implantation and replaced https://github.com/contao-community-alliance/dc-general/pull/368.
> [RTM] Feature: Implement the own file selector popup

- src/ContaoCommunityAlliance/DcGeneral/Contao/Callback/ModelLabelCallbackListener.php
The original table driver treats the label callback differently. In table mode, an array is expected as a return value. In the other modes, a string is expected as a return value.
See non table mode:
https://github.com/contao/core/blob/master/system/modules/core/drivers/DC_Table.php#L3732
See table mode:
https://github.com/contao/core/blob/master/system/modules/core/drivers/DC_Table.php#L4701
> [WIP] Make the legacy model label callback listener compatible

- src/ContaoCommunityAlliance/DcGeneral/Contao/Subscriber/FallbackResetSubscriber.php
Hotfix reset fallback PR #321
see https://github.com/MetaModels/core/issues/1213
the implementation in PR #321 has a bug in https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Contao/Subscriber/FallbackResetSubscriber.php#L90
this method should reset the parameter e.g. "isdefault" only if the new item is set as default (=1)
```diff
private function handleFallback(AbstractModelAwareEvent $event)
{
$model        = $event->getModel();
$dataProvider = $event->getEnvironment()->getDataProvider($model->getProviderName());
$properties   = $event->getEnvironment()->getDataDefinition()->getPropertiesDefinition();
foreach (array_keys($model->getPropertiesAsArray()) as $propertyName) {
if (!$properties->hasProperty($propertyName)) {
continue;
} …
```
> [RTM] Hotfix reset fallback PR #321

- src/ContaoCommunityAlliance/DcGeneral/Contao/Dca/Builder/Legacy/LegacyDcaDataDefinitionBuilder.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/Subscriber/FallbackResetSubscriber.php
- src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php
- src/ContaoCommunityAlliance/DcGeneral/Data/ModelManipulator.php
- src/ContaoCommunityAlliance/DcGeneral/DataDefinition/Definition/Properties/DefaultProperty.php
- src/ContaoCommunityAlliance/DcGeneral/DataDefinition/Definition/Properties/EmptyValueAwarePropertyInterface.php
This adds a new interface `EmptyValueAwarePropertyInterface` for properties to keep the ABI compatible.
The purpose of this property is to allow defining of an "empty" value which get's used instead of an empty string when saving property values.
This should help us to circumvent the MySQL strict mode problems we encounter currently.
> [RFC] Add empty value aware property information

- src/Contao/View/Contao2BackendView/ButtonRenderer.php
Check whether icon is part of the contao theme. If so, use a different suffix fo the disabled icon.
This actually is a hotifx.
Prior this commit, the disabled versions of delete.svg, copy.svg etc weren't displayed because such icons use `_.svg` as a suffix and not `_1.svg`
> Display disabled icons for copy, delete, add etc. 

- src/EventListener/ModelRelationship/TreeEnforcingListener.php
This PR fixes https://sentry.io/share/issue/c534a8150cbd47e695d571c2af5c70aa/.
The identical check was introduced in https://github.com/contao-community-alliance/dc-general/commit/b5a9bc9c3267542a0d3058cb457e9ac72519956b#diff-f987bad0dfd2c3431313a2460e448563.
> Check for parent model being null.

- src/Data/DefaultDataProviderDBalUtils.php
Quote column names in select and do not add id property twice.
Fixes https://sentry.io/share/issue/e16a1d84dcf14ba999189a0e07cd5313/.
```
An exception occurred while executing 'SELECT id, id, pid, sorting, tstamp, published, dcatype, attr_id, tl_class, legendhide, legendtitle, mandatory, alwaysSave, filterable, searchable, chosen, allowHtml, preserveTags, decodeEntities, rte, rows, cols, trailingSlash, spaceToUnderscore, includeBlankOption, submitOnChange, readonly, fe_widget, doNotOverwrite, useHomeDir, fallbackImage, select_as_radio, select_minLevel, select_maxLevel, tag_as_wizard, tag_minLevel, tag_maxLevel, rgxp, thumbnailSize FROM tl_metamodel_dcasetting WHERE tl_metamodel_dcasetting.id=?' with params ["117"]:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error …
```
> Quote column names in select and do not add id property twice.

- src/Exception/DefinitionException.php
- src/Exception/EditOnlyModeException.php
- src/Exception/NotCreatableException.php
- src/Exception/NotDeletableException.php
- src/Exception/NotEditableException.php
- src/deprecated-autoload.php
Move exceptions, and add `NotEditableException` as stated in https://github.com/contao-community-alliance/dc-general-contao-frontend/pull/19#issuecomment-478007507.
> Exception handling

- src/Panel/DefaultLimitElement.php
Fix a problem where the value for setOffset($offset) is not a int value. This should fix the problem where the selected value of the limit select wasn't set correct.
> Force int value for "setOffset($offset)"

- src/Panel/DefaultLimitElement.php
Behavior:
The value "tl_limit" of the limit field will be handled as "all". 
Problem: 
If you set up a filter with no result the selected value of the limit field will be 'tl_limit' if you now reset the filter back, the limit will still be "tl_limit" which mean i will get all result after a filter reload. So if you have 20k entries in the list, the system isn't able to display this data. 
Fix: 
I change the handling that the value "tl_limit" will be handled as nothing. So the system can use the default handling.
> Change the handling of tl_limit for the DefaultLimitElement

- src/Data/DefaultDataProvider.php
* `DefaultDataProvider#getVersions()` has typos: `formTable` instead of `fromTable`. `fetch()` should be `fetchAll()`, as is evident by subsequent iteration expecting result rows.
* `getActiveVersion` has a typo (`select(['select'])` should be selecting `'version'`).
* `getVersion()` is missing a select.
To quickly reproduce the issues, change `dataContainer` to `General` in any Contao core DCA that has versioning enabled, for example `tl_theme`. First exception coming from the `formTable` typo:
> An exception occurred while executing 'SELECT tstamp, version, username, active FROM tl_version WHERE (tl_version.formTable = ?) AND (tl_version.pid = ?) ORDER BY tl_version.version DESC' with params ["tl_theme", "1"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tl_version.formTable' …
> Fix version data retrieval in DefaultDataProvider

- src/Contao/View/Contao2BackendView/TreePicker.php
This adds the fallback to use `id` as id property if none has been defined as already used in `TreePicker::renderItemsPlain()`.
If no id property has been passed via URL, we get a popup display showing all entries as selected (as id property is `null`, the value of the property named `null` in the model is also `null` and hence we compare  `null == null` for testing if the id has been checked).
> Add fallback for id property in tree picker

- src/Controller/ModelCollector.php
Fix an error where the hierarchical detection find the wrong condition and
used the parent id list instead of the hierarchical one.
> Fix for paste button

- .check-author.yml
- .gitignore
- src/Contao/View/Contao2BackendView/EditMask.php
Fix empty id in URL with new HTLM encoding in Contao 4.9
> Fix empty id in URL with new HTLM encoding in Contao 4.9

- src/Contao/View/Contao2BackendView/Subscriber/GetGroupHeaderSubscriber.php
- src/Resources/contao/languages/de/default.php
- src/Resources/contao/languages/en/default.php
Implements the backend grouping by week
replaces #533
> Add grouping by week (replaces #533)

- src/Contao/View/Contao2BackendView/ContaoWidgetManager.php
This fixes to pass encoded values when updating the model.
As the model can only store native values, we need to convert from widget to model value before.
> Pass encoded property values when updating model

- .phpcq.yaml.dist
- src/Contao/View/Contao2BackendView/TreePicker.php
- src/Contao/View/Contao2BackendView/Widget/FileTree.php
- src/Resources/contao/templates/widget_common_picker.html5
- src/Resources/contao/templates/widget_treepicker.html5
Fix tree picker: this prevents crosstalk with fields that have the same name in the mask as in the picker
> Fix tree picker: this prevents crosstalk
