contao-community-alliance/dc-general

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php
> fix for MetaModels/core#709

- contao/templates/dcbe_general_edit.html5
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php
As discussed here https://github.com/contao-community-alliance/dc-general/issues/101 we can now add the breadcrumb to the editmask.
> Added the breadcrumb to the editmask

- src/ContaoCommunityAlliance/DcGeneral/Data/DatabaseUuidIdGenerator.php
- src/ContaoCommunityAlliance/DcGeneral/Data/DefaultDataProvider.php
- src/ContaoCommunityAlliance/DcGeneral/Data/IdGeneratorInterface.php
As discussed yesterday a have reworked the idGenerator a litte bit. Now it is possible to pass the idGenerator instance in the DCA-Config. So it is possible to change it easy to another generator.
I have changed the IdGeneratorInterface to fit to this new way.
@discordier please have a look on it and give feedback :)
> added more flexibility to the idgeneration

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Filter/LanguageFilter.php
- src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php
This pull requests fixes the issues with the save buttons "save and new" and "save and back" (See #86 and #29).
> Save buttons

- src/ContaoCommunityAlliance/DcGeneral/Contao/Dca/Builder/Legacy/LegacyDcaDataDefinitionBuilder.php
I stumpled upon an issue that the same sorting definition could be created twice when setting a default sorting in (list.sorting.fields) (See https://github.com/MetaModels/core/pull/818#issuecomment-114256239)
This pull requests handles it by passing the information from the list sorting parser to the property sorting parser.
> Avoid duplicate sorting entries when parsing the dca.

- contao/config/event_listeners.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Event/GetGroupHeaderEvent.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Subscriber/GetGroupHeaderSubscriber.php
Extract group heading formatting to a separate subscriber.
> Extract group heading handling to separate subscriber

- contao/html/js/vanillaGeneral.js
This pull requests changes the simple pull request detection (See #82).
> Change simple modal detection.

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Event/GetParentHeaderEvent.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ParentView.php
This pull request improves the header fields by translating the tstamp. It also passes the parent model to the triggered event. 
This is part of the proposed solution for metamodels/core#184
> Improve the header fields.

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php
Necessary for https://github.com/MetaModels/core/pull/827
> ListView fix: Use columns from label formatter

- composer.json
- src/ContaoCommunityAlliance/DcGeneral/DC_General.php
This pull request provides the translator as service. This can be useful when the environment isn't build yet, e.g. in https://github.com/MetaModels/core/blob/tng/src/MetaModels/DcGeneral/Dca/Builder/Builder.php
> Introduce a service for the translator.

- src/ContaoCommunityAlliance/DcGeneral/BaseConfigRegistry.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Widget/FileTree.php
@discordier requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/contao-community-alliance/dc-general/
> Scrutinizer Auto-Fixes

- contao/templates/dcbe_general_listView.html5
- contao/templates/dcbe_general_listView_sorting.html5
- src/ContaoCommunityAlliance/DcGeneral/Data/DefaultCollection.php
This PR fixes the issue described in https://github.com/MetaModels/core/issues/922.
I don't know if the changes in https://github.com/contao-community-alliance/dc-general/commit/001fb5d7b4e68dbfcc7fc5f0b4715e2b9b862387 will have any unexpected side effects. This change is required because a new empty model will be pasted into the collection when calling the paste top action.
> Hotfix missing insert into icons

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php
> [WIP] add ACE support and TinyMCE4

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Controller/ClipboardController.php
This is an fix for https://github.com/contao-community-alliance/dc-general/pull/296
> if statement is adding allowed don´t test is not

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/SelectHandler.php
> Remove the global commands by action select. We need the back button only

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php
> support for use multiple rich text editor in the same edit mask

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/GlobalButtonRenderer.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php
hotfix CSS tl_buttons_a to tl_buttons for Contao 4 compatibility
> hotfix CSS tl_buttons_a to tl_buttons for Contao 4 compatibility

- contao/config/event_subscribers.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/Dca/Builder/Legacy/ExtendedLegacyDcaDataDefinitionBuilder.php
- src/ContaoCommunityAlliance/DcGeneral/Contao/Subscriber/DynamicParentTableSubscriber.php
- src/ContaoCommunityAlliance/DcGeneral/DataDefinition/Definition/BasicDefinitionInterface.php
- src/ContaoCommunityAlliance/DcGeneral/DataDefinition/Definition/DefaultBasicDefinition.php
- src/ContaoCommunityAlliance/DcGeneral/DataDefinition/Definition/View/DefaultListingConfig.php
- src/ContaoCommunityAlliance/DcGeneral/DataDefinition/Definition/View/ListingConfigInterface.php
The missing support for dynamic parent table
> [RTM] Support dynamic parent table

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ButtonRenderer.php
> [RTM] Add the missing key by define the operation button event

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php
> [WIP] Make values from tree picker sortable

- src/ContaoCommunityAlliance/DcGeneral/Contao/Callback/PropertyInputFieldGetXLabelCallbackListener.php
Return the right args for the xlabel callback from this listener
> [WIP] Return the right args for the xlabel callback from this listener

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Widget/FileTree.php
It may be possible that there are no files available because the values may be zero.
> [RTM] Files can be null in the file tree

- src/ContaoCommunityAlliance/DcGeneral/Contao/Dca/Builder/Legacy/LegacyDcaDataDefinitionBuilder.php
> [WIP] Add automation by legacy builder for order properties

- src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax.php
> [WIP] Use by execute post action the active model

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ButtonRenderer.php
Hotfix add HTML class at buttons in list view
> [RTM] Hotfix add HTML class at buttons

- src/Contao/View/Contao2BackendView/ActionHandler/AbstractListShowAllHandler.php
- src/Contao/View/Contao2BackendView/ActionHandler/ParentedListViewShowAllHandler.php
These improvements are necessary creating my own ListViewHandler which `extends ParentedListViewShowAllHandler`.
> [RTM] Improvements when implementing own parented list view handler

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Filter/LanguageFilter.php
fix save default language in session at create item
#395
> [RTM] hotfix #395 - do not store language per item

- src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Widget/FileTree.php
This fix solve a problem where the FileTree-Widget can't sort the files.
> [RTM] Fix file sorting

- src/Contao/View/Contao2BackendView/Subscriber/WidgetBuilder.php
> Minor SCA fixes.

- build.xml
- src/Controller/ModelCollector.php
Hotfix NOT rule at view condition
see https://github.com/MetaModels/core/issues/1365
> Hotfix NOT rule at view condition

- src/Contao/View/Contao2BackendView/ActionHandler/ToggleHandler.php
> Manually set id on original model after cloning

- src/Contao/View/Contao2BackendView/ContaoWidgetManager.php
hotfix check path for own tinyMCE template
fix https://github.com/contao-community-alliance/dc-general/issues/508
> hotfix check path for own tinyMCE template

- src/Data/DefaultDataProviderDBalUtils.php
Change operations to fix DBAL error
see #549
> Change operations to fix DBAL error

- src/Resources/contao/templates/dcbe_general_common_list.html5
Fix backend table template with grouping
Change table generating to one table witch separated tbodys and add grouping information as row
> [RTM] Fix backend table template with grouping

- src/Contao/View/Contao2BackendView/TreePicker.php
- src/Contao/View/Contao2BackendView/Widget/FileTree.php
- src/Resources/contao/templates/widget_common_picker.html5
- src/Resources/contao/templates/widget_filetree.html5
Fix readonly for filetree picker and item picker (select and tags)
> Fix readonly for filetree picker and item picker (select and tags)

- src/Resources/contao/templates/dcbe_general_panel_search.html5
> [RTM] Fix CSS class in search panel

- .github/workflows/diagnostics.yml
- composer.json
- src/Contao/View/Contao2BackendView/ActionHandler/CreateHandler.php
- src/Contao/View/Contao2BackendView/ActionHandler/EditHandler.php
- src/Contao/View/Contao2BackendView/EditMask.php
- src/Resources/config/contao/handler_backend_listeners.yml
Add editInformation to EditMask to cancel saving from PrePersist
> [RTM] Add editInformation to EditMask to cancel saving from PrePersist

- .check-author.yml
- .github/workflows/diagnostics.yml
- composer.json
- tests/Controller/ModelCollectorTest.php
> [RTM] Fix unit tests

- .check-author.yml
- src/Contao/View/Contao2BackendView/EditMask.php
Set widget to readonly if not editable
> Set widget to readonly if not editable

- src/Contao/View/Contao2BackendView/ButtonRenderer.php
Fix type save call at renderImageAsHtml
see https://community.contao.org/de/showthread.php?83829-Beim-anlegen-eine-Filterset-l%C3%B6st-Internal-Server-Error-am-Webhosting-aus
> Fix type save call at renderImageAsHtml

- composer.json
- Add version ^2.1 for the doctrine/cache
> Correct the version for doctrine/cache

- src/Contao/View/Contao2BackendView/TreePicker.php
> Fix phpwarning treepicker

- src/Data/DefaultDataProvider.php
Add sorting filteritems
fix https://github.com/MetaModels/core/issues/1432
> [LGTM] Add sorting filteritems

- src/Contao/View/Contao2BackendView/ActionHandler/ShowHandler.php
Add default columns at show
Fix https://github.com/MetaModels/core/issues/1131
We should add at ModelInterface `getDefaultProperties()`
> [LGTM] Add defaultcols at show

- src/Contao/View/Contao2BackendView/EditMask.php
- src/Contao/View/Contao2BackendView/Event/GetEditMaskSubHeadlineEvent.php
- src/Contao/View/Contao2BackendView/EventListener/CreateSubHeadlineListener.php
- src/Resources/config/contao/event_common_subscribers.yml
Add sub-headline event for input mask
see https://github.com/MetaModels/contao-frontend-editing/issues/43
> [RTM] Add sub-headline event

- src/Contao/View/Contao2BackendView/ContaoWidgetManager.php
> [LGTM] fix translation datepicker

- src/Contao/Event/Subscriber.php
Fix check if string in subscriber
> [LGTM] Fix check if string in subscriber

- src/Contao/View/Contao2BackendView/EditMask.php
- src/Contao/View/Contao2BackendView/EventListener/ColorPickerWizardListener.php
- src/Contao/View/Contao2BackendView/Subscriber/WidgetBuilder.php
- src/Contao/View/Contao2BackendView/TreePicker.php
- src/Contao/View/Contao2BackendView/TreeView.php
- src/Resources/contao/templates/dcbe_general_treeview.html5
Fix translation editmask and other
> [LGTM] Fix translation editmask and other

- src/Resources/contao/languages/de/default.php
- src/Resources/contao/languages/en/default.php
> [LGTM] Add language key 'newRecord'

- src/Resources/contao/templates/dcbe_general_language_selector.html5
Fix panel for fallback language
> [LGTM] Fix panel for fallback language

- src/Contao/View/Contao2BackendView/ActionHandler/ShowHandler.php
Fix showhandler for standard columns
> Fix showhandler for standard columns

- src/Contao/View/Contao2BackendView/EditMask.php
Fix show languages at untranslated models in edit mask
> Fix show languages at untranslated models in edit mask

- src/Contao/View/Contao2BackendView/ContaoWidgetManager.php
Add readonly for tinyMCE and ACE editor
relatet with PR https://github.com/contao/contao/pull/5985
> Add readonly for tinyMCE and ACE editor

- .check-author.yml
- src/Data/DefaultDataProviderDBalUtils.php
> Fix filter IN/NOTIN

- src/Panel/DefaultSearchElement.php
Fix PHP 8 warning search panel
> Fix PHP 8 warning search panel

- src/Contao/Subscriber/FormatModelLabelSubscriber.php
Error occures with empty timestamps in rendered listing.
> Fix undefined array key problem

- src/Panel/DefaultLimitElement.php
Fix limit of list - currently the pagination limits are not observed and all values are output.
> Fix limit of list

- src/Contao/Dca/Populator/BackendViewPopulator.php
- src/Contao/View/Contao2BackendView/ActionHandler/AbstractListShowAllHandler.php
- src/Contao/View/Contao2BackendView/ActionHandler/ShowHandler.php
- src/Contao/View/Contao2BackendView/TreeView.php
- src/Resources/config/contao/handler_backend_listeners.yml
- src/Resources/config/contao/handler_multiple_backend_listeners.yml
- src/Resources/config/services.yml
- src/Resources/contao/templates/dcbe_general_common_list.html5
- src/Resources/contao/templates/dcbe_general_edit.html5
- src/Resources/contao/templates/dcbe_general_language_panel.html5
- src/Resources/contao/templates/dcbe_general_panel.html5
- src/Resources/contao/templates/dcbe_general_treeview.html5
- src/Resources/contao/templates/widget_common_picker.html5
- src/Resources/contao/templates/widget_filetree.html5
Fix request token at change language
> Fix request token at change language

- src/Resources/contao/templates/dc_general_wizard_common_picker.html5
- src/Resources/contao/templates/dcbe_general_clipboard.html5
- src/Resources/contao/templates/dcbe_general_field.html5
- src/Resources/contao/templates/dcbe_general_panel_filter.html5
- src/Resources/contao/templates/dcbe_general_panel_limit.html5
- src/Resources/contao/templates/dcbe_general_panel_sort.html5
- src/Resources/contao/templates/dcbe_general_panel_submit.html5
- src/Resources/contao/templates/dcbe_general_show.html5
- src/Resources/contao/templates/dcbe_general_treeview_child.html5
- src/Resources/contao/templates/dcbe_general_treeview_entry.html5
- src/Resources/contao/templates/widget_treepicker.html5
- src/Resources/contao/templates/widget_treepicker_child.html5
- src/Resources/contao/templates/widget_treepicker_entry.html5
- src/Resources/contao/templates/widget_treepicker_popup.html5
> Fix code style in templates

- src/Contao/Callback/Callbacks.php
> Fix issue 617

- src/Contao/Callback/Callbacks.php
- src/Contao/Compatibility/DcCompat.php
- src/Contao/Dca/Builder/Legacy/LegacyDcaDataDefinitionBuilder.php
- src/Contao/View/Contao2BackendView/ActionHandler/MultipleHandler/OverrideAllHandler.php
- src/Contao/View/Contao2BackendView/EditMask.php
- src/Contao/View/Contao2BackendView/Widget/AbstractWidget.php
- src/DC/General.php
- src/DataContainerInterface.php
- src/Panel/DefaultLimitElement.php
> Fix rebase from pr 608

- src/Contao/Callback/Callbacks.php
- src/Contao/Compatibility/DcCompat.php
- src/Contao/Dca/Builder/Legacy/LegacyDcaDataDefinitionBuilder.php
- src/Contao/View/Contao2BackendView/ActionHandler/MultipleHandler/OverrideAllHandler.php
- src/Contao/View/Contao2BackendView/EditMask.php
- src/Contao/View/Contao2BackendView/Subscriber/GetGroupHeaderSubscriber.php
- src/Contao/View/Contao2BackendView/Widget/AbstractWidget.php
- src/DC/General.php
- src/DataContainerInterface.php
- src/Panel/DefaultLimitElement.php
Fix group per week: code style
> Fix group per week

- src/Contao/View/Contao2BackendView/TreePicker.php
- src/Contao/View/Contao2BackendView/TreeView.php
- src/Contao/View/Contao2BackendView/Widget/PageTree.php
- src/Controller/BackendTreeController.php
> Fix TreePicker

- src/Contao/Callback/ModelLabelCallbackListener.php
Fix label-callback at treepicker-popup
see https://github.com/contao-community-alliance/dc-general/issues/627
> Fix label-callback at treepicker-popup

- src/Contao/View/Contao2BackendView/TreePicker.php
- src/Resources/contao/templates/widget_treepicker_popup.html5
Please explain the detailed changes you made here.
Reference any issue number this pull request fixes.
> Treepicker popup fix

- src/Contao/View/Contao2BackendView/ContaoWidgetManager.php
- src/Contao/View/Contao2BackendView/Subscriber/WidgetBuilder.php
- src/Contao/View/Contao2BackendView/TreeSelect.php
- src/Data/ConfigInterface.php
- src/Data/DefaultConfig.php
- src/Data/DefaultDataProvider.php
- src/Data/TableRowsAsRecordsDataProvider.php
- src/Resources/config/contao/widget_backend_listeners.yml
Fix translation handling for label and description and fixes for PHPCQ
> Fix translation handling for label and description and fixes for PHPCQ

- src/Contao/Picker/PagePickerProvider.php
- src/Controller/BackendTreeController.php
> Fix picker for pages and load language file

- src/Contao/View/Contao2BackendView/ActionHandler/CopyHandler.php
- src/Contao/View/Contao2BackendView/ViewHelpers.php
> Fix the wrong backend route while copying

- src/Contao/View/Contao2BackendView/ContaoWidgetManager.php
- src/Contao/View/Contao2BackendView/EditMask.php
- src/Controller/ControllerInterface.php
Fix encoding and decoding for widgets
> Fix encoding and decoding for widgets

- src/Contao/View/Contao2BackendView/ActionHandler/AbstractListShowAllHandler.php
- src/Contao/View/Contao2BackendView/ActionHandler/CopyHandler.php
- src/Contao/View/Contao2BackendView/PanelRenderer.php
- src/Resources/contao/templates/dcbe_general_clipboard.html5
- src/Resources/contao/templates/dcbe_general_common_list.html5
- src/Resources/contao/templates/dcbe_general_edit.html5
- src/Resources/contao/templates/dcbe_general_field.html5
- src/Resources/contao/templates/dcbe_general_language_panel.html5
- src/Resources/contao/templates/dcbe_general_language_selector.html5
- src/Resources/contao/templates/dcbe_general_panel.html5
- src/Resources/contao/templates/dcbe_general_panel_limit.html5
- src/Resources/contao/templates/dcbe_general_panel_search.html5
- src/Resources/contao/templates/dcbe_general_panel_sort.html5
- src/Resources/contao/templates/dcbe_general_panel_submit.html5
- src/Resources/contao/templates/dcbe_general_show.html5
- src/Resources/contao/templates/dcbe_general_treeview.html5
- src/Resources/contao/templates/widget_common_picker.html5
- src/Resources/contao/templates/widget_filetree.html5
> fix translation for buttons

- src/Contao/Factory/SessionStorageFactory.php
- src/Contao/Picker/AbstractAwarePickerProvider.php
- src/Contao/Picker/PagePickerProvider.php
- src/Contao/Picker/TreePickerProvider.php
- src/Contao/View/Contao2BackendView/Controller/ClipboardController.php
- src/Contao/View/Contao2BackendView/Filter/LanguageFilter.php
- src/Contao/View/Contao2BackendView/Subscriber/CheckPermission.php
- src/ContaoManager/Plugin.php
- src/Resources/config/services.yml
> Fix deprecation warnings

- src/Contao/View/Contao2BackendView/ActionHandler/MultipleHandler/EditAllHandler.php
- src/Contao/View/Contao2BackendView/Subscriber/MultipleHandlerSubscriber.php
- src/View/ActionHandler/AbstractPropertyVisibilityHandler.php
Fix edit all when containing MCW and fix PHP 8 warning
> Fix edit all when containing MCW and fix PHP 8 warning

- src/Contao/View/Contao2BackendView/ActionHandler/MultipleHandler/OverrideAllHandler.php
- src/Contao/View/Contao2BackendView/ActionHandler/MultipleHandler/SelectPropertyAllHandler.php
> Fix OverrideAllHandler.php

- src/Contao/View/Contao2BackendView/Filter/LanguageFilter.php
- src/Resources/contao/templates/dcbe_general_language_selector.html5
Add preset language with GET parameter
> Add preset language with GET parameter

- src/Contao/View/Contao2BackendView/TreePicker.php
- src/Resources/contao/templates/widget_treepicker_entry.html5
- src/Resources/contao/templates/widget_treepicker_popup.html5
Fix tree picker for language support
> Fix tree picker for language support

- src/Contao/View/Contao2BackendView/ContaoWidgetManager.php
- src/Contao/View/Contao2BackendView/Widget/FileTree.php
- src/Controller/BackendTreeController.php
> Fix for PHPCQ

- src/Contao/View/Contao2BackendView/ActionHandler/PasteHandler.php
see https://github.com/MetaModels/core/issues/1405
> Fix move item if clipboard not empty

- src/Contao/Dca/Populator/ParentDefinitionPopulator.php
- src/Contao/View/Contao2BackendView/ContaoWidgetManager.php
- src/Contao/View/Contao2BackendView/EditMask.php
- src/Event/ValidateModelEvent.php
- src/Resources/contao/templates/dcbe_general_edit.html5
The event can be used to check the entire model and pass error messages for one or more properties
> Add new ValidateModelEvent

- src/BaseConfigRegistry.php
- src/Contao/View/Contao2BackendView/TreePicker.php
Fix tree picker at parent view
> Fix tree picker at parent view

- src/Resources/contao/templates/dcbe_general_edit.html5
> Fix template override all
